{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "beca1964-2385-4fce-9a74-91e18e9c1375",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "d48aea88924a4f019a2f0fc24bd121c5",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Map:   0%|          | 0/5000 [00:00<?, ? examples/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4684/3349004995.py:92: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.\n",
      "  trainer = Trainer(\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "\n",
       "    <div>\n",
       "      \n",
       "      <progress value='3162' max='3162' style='width:300px; height:20px; vertical-align: middle;'></progress>\n",
       "      [3162/3162 09:12, Epoch 2/2]\n",
       "    </div>\n",
       "    <table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       " <tr style=\"text-align: left;\">\n",
       "      <th>Epoch</th>\n",
       "      <th>Training Loss</th>\n",
       "      <th>Validation Loss</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>1</td>\n",
       "      <td>0.290800</td>\n",
       "      <td>1.980698</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>2</td>\n",
       "      <td>0.165000</td>\n",
       "      <td>2.917709</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table><p>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": [
       "('./qa_model_2_roberta/tokenizer_config.json',\n",
       " './qa_model_2_roberta/special_tokens_map.json',\n",
       " './qa_model_2_roberta/vocab.json',\n",
       " './qa_model_2_roberta/merges.txt',\n",
       " './qa_model_2_roberta/added_tokens.json',\n",
       " './qa_model_2_roberta/tokenizer.json')"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from transformers import AutoTokenizer, AutoModelForQuestionAnswering, Trainer, TrainingArguments\n",
    "from datasets import load_dataset, DatasetDict\n",
    "import torch\n",
    "\n",
    "\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(\n",
    "    level=logging.INFO,\n",
    "    format=\"%(asctime)s - %(levelname)s - %(message)s\"\n",
    ")\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "\n",
    "\n",
    "model_name = \"deepset/roberta-base-squad2\"\n",
    "tokenizer = AutoTokenizer.from_pretrained(model_name)\n",
    "model = AutoModelForQuestionAnswering.from_pretrained(model_name)\n",
    "\n",
    "data = load_dataset(\"squad_v2\")\n",
    "\n",
    "train_data= data[\"train\"].shuffle(seed=42).select(range(25000))\n",
    "val_data = data[\"validation\"].shuffle(seed=42).select(range(5000))\n",
    "\n",
    "small_data = DatasetDict({\n",
    "    \"train\": train_data,\n",
    "    \"validation\": val_data,\n",
    "})\n",
    "\n",
    "def preprocess(examples):\n",
    "    questions = [q.strip() for q in examples[\"question\"]]\n",
    "    inputs = tokenizer(\n",
    "    questions,\n",
    "    examples[\"context\"],\n",
    "    truncation=\"only_second\",\n",
    "    max_length= 384,\n",
    "    padding=\"max_length\",\n",
    "    return_offsets_mapping=True,\n",
    "    return_overflowing_tokens=True,\n",
    "    )\n",
    "    offset_mapping = inputs.pop(\"offset_mapping\")\n",
    "    sample_overflow = inputs.pop(\"overflow_to_sample_mapping\")\n",
    "    start_positions =[]\n",
    "    end_positions =[]\n",
    "\n",
    "    for i, offset in enumerate(offset_mapping):\n",
    "        input_ids = inputs[\"input_ids\"][i]\n",
    "        cls_indx = input_ids.index(tokenizer.cls_token_id)\n",
    "        sequence_ids = inputs.sequence_ids(i)\n",
    "        sample_idx = sample_overflow[i]\n",
    "        answer = examples[\"answers\"][sample_idx]\n",
    "\n",
    "        if len(answer[\"answer_start\"]) ==0:\n",
    "            start_positions.append(cls_indx)\n",
    "            end_positions.append(cls_indx)\n",
    "            continue\n",
    "\n",
    "        start_char = answer[\"answer_start\"][0]\n",
    "        end_char = start_char + len(answer[\"text\"][0])\n",
    "        start_token_idx = 0\n",
    "        while sequence_ids[start_token_idx] !=1:\n",
    "            start_token_idx +=1\n",
    "\n",
    "        end_token_idx = len(input_ids) -1\n",
    "        while sequence_ids[end_token_idx] !=1:\n",
    "            end_token_idx -=1\n",
    "\n",
    "        if not (offset[start_token_idx][0] <= start_char and\n",
    "        offset[end_token_idx][1] >end_char ):\n",
    "            start_positions.append(cls_indx)\n",
    "            end_positions.append(cls_indx)\n",
    "\n",
    "        else:\n",
    "            while offset[start_token_idx][0] <=start_char:\n",
    "                start_token_idx +=1\n",
    "            start_positions.append(start_token_idx -1)\n",
    "\n",
    "            while offset[end_token_idx][1] > end_char:\n",
    "                end_token_idx -=1\n",
    "            end_positions.append(end_token_idx +1)\n",
    "\n",
    "    inputs[\"start_positions\"] = start_positions\n",
    "    inputs[\"end_positions\"] = end_positions\n",
    "    return inputs\n",
    "\n",
    "\n",
    "tokenized_data = small_data.map(preprocess, batched=True, remove_columns=small_data[\"train\"].column_names)\n",
    "\n",
    "training_args = TrainingArguments(\n",
    "    output_dir=\"./qa_model_2_roberta\",\n",
    "    per_device_train_batch_size=16,\n",
    "    per_device_eval_batch_size=16,\n",
    "    num_train_epochs=2,\n",
    "    eval_strategy=\"epoch\",\n",
    "    save_strategy=\"epoch\",\n",
    "    learning_rate=3e-5,\n",
    "    weight_decay=0.05,\n",
    "    load_best_model_at_end=True,\n",
    "    fp16=True, \n",
    "    \n",
    ")        \n",
    "\n",
    "trainer = Trainer(\n",
    "    model=model,\n",
    "    args=training_args,\n",
    "    train_dataset=tokenized_data[\"train\"],\n",
    "    eval_dataset=tokenized_data[\"validation\"],\n",
    "    tokenizer=tokenizer,\n",
    ")\n",
    "\n",
    "def main():\n",
    "    trainer.train()\n",
    "    trainer.save_model(\"./qa_model_2_roberta\")\n",
    "    tokenizer.save_pretrained(\"./qa_model_2_roberta\")\n",
    "\n",
    "\n",
    "if __name__ ==\"__main__\":\n",
    "    main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "5ff0a783-b5ec-46b9-9978-9ce33472c6ae",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'exact': 41.04, 'f1': 41.486402045907326, 'total': 5000, 'HasAns_exact': 0.40338846308995563, 'HasAns_f1': 1.3037556391837617, 'HasAns_total': 2479, 'NoAns_exact': 80.9996033320111, 'NoAns_f1': 80.9996033320111, 'NoAns_total': 2521, 'best_exact': 50.42, 'best_exact_thresh': 0.0, 'best_f1': 50.42, 'best_f1_thresh': 0.0}\n"
     ]
    }
   ],
   "source": [
    "import logging\n",
    "from transformers import (\n",
    "    AutoTokenizer,\n",
    "    AutoModelForQuestionAnswering,\n",
    "    Trainer,\n",
    "    TrainingArguments,\n",
    ")\n",
    "from datasets import load_dataset, DatasetDict\n",
    "\n",
    "\n",
    "logging.basicConfig(\n",
    "    level=logging.INFO,\n",
    "    format=\"%(asctime)s - %(levelname)s - %(message)s\"\n",
    ")\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "\n",
    "def preprocess(examples, tokenizer):\n",
    "    questions = [q.strip() for q in examples[\"question\"]]\n",
    "\n",
    "    inputs = tokenizer(\n",
    "        questions,\n",
    "        examples[\"context\"],\n",
    "        truncation=\"only_second\",\n",
    "        max_length=384,\n",
    "        padding=\"max_length\",\n",
    "        return_offsets_mapping=True,\n",
    "        return_overflowing_tokens=True,\n",
    "    )\n",
    "\n",
    "    offset_mapping = inputs.pop(\"offset_mapping\")\n",
    "    sample_overflow = inputs.pop(\"overflow_to_sample_mapping\")\n",
    "\n",
    "    start_positions = []\n",
    "    end_positions = []\n",
    "\n",
    "    for i, offsets in enumerate(offset_mapping):\n",
    "        input_ids = inputs[\"input_ids\"][i]\n",
    "        cls_idx = input_ids.index(tokenizer.cls_token_id)\n",
    "\n",
    "        sequence_ids = inputs.sequence_ids(i)\n",
    "        sample_idx = sample_overflow[i]\n",
    "        answer = examples[\"answers\"][sample_idx]\n",
    "\n",
    "        # no-answer\n",
    "        if len(answer[\"answer_start\"]) == 0:\n",
    "            start_positions.append(cls_idx)\n",
    "            end_positions.append(cls_idx)\n",
    "            continue\n",
    "\n",
    "        start_char = answer[\"answer_start\"][0]\n",
    "        end_char = start_char + len(answer[\"text\"][0])\n",
    "\n",
    "        token_start = 0\n",
    "        while sequence_ids[token_start] != 1:\n",
    "            token_start += 1\n",
    "\n",
    "        token_end = len(input_ids) - 1\n",
    "        while sequence_ids[token_end] != 1:\n",
    "            token_end -= 1\n",
    "\n",
    "        if not (\n",
    "            offsets[token_start][0] <= start_char\n",
    "            and offsets[token_end][1] >= end_char\n",
    "        ):\n",
    "            start_positions.append(cls_idx)\n",
    "            end_positions.append(cls_idx)\n",
    "            continue\n",
    "\n",
    "        while offsets[token_start][0] <= start_char:\n",
    "            token_start += 1\n",
    "        start_positions.append(token_start - 1)\n",
    "\n",
    "        while offsets[token_end][1] >= end_char:\n",
    "            token_end -= 1\n",
    "        end_positions.append(token_end + 1)\n",
    "\n",
    "    inputs[\"start_positions\"] = start_positions\n",
    "    inputs[\"end_positions\"] = end_positions\n",
    "    return inputs\n",
    "\n",
    "\n",
    "def main():\n",
    "    logger.info(\"Loading model and tokenizer\")\n",
    "    model_name = \"deepset/roberta-base-squad2\"\n",
    "    tokenizer = AutoTokenizer.from_pretrained(model_name)\n",
    "    model = AutoModelForQuestionAnswering.from_pretrained(model_name)\n",
    "\n",
    "    logger.info(\"Loading dataset\")\n",
    "    data = load_dataset(\"squad_v2\")\n",
    "\n",
    "    train_data = data[\"train\"].shuffle(seed=42).select(range(25000))\n",
    "    val_data = data[\"validation\"].shuffle(seed=42).select(range(5000))\n",
    "\n",
    "    dataset = DatasetDict({\n",
    "        \"train\": train_data,\n",
    "        \"validation\": val_data,\n",
    "    })\n",
    "\n",
    "    logger.info(\"Preprocessing dataset\")\n",
    "    tokenized = dataset.map(\n",
    "        lambda x: preprocess(x, tokenizer),\n",
    "        batched=True,\n",
    "        remove_columns=dataset[\"train\"].column_names,\n",
    "    )\n",
    "\n",
    "    training_args = TrainingArguments(\n",
    "        output_dir=\"./qa_model_2_roberta\",\n",
    "        per_device_train_batch_size=16,\n",
    "        per_device_eval_batch_size=16,\n",
    "        num_train_epochs=2,\n",
    "        evaluation_strategy=\"epoch\",\n",
    "        save_strategy=\"epoch\",\n",
    "        learning_rate=3e-5,\n",
    "        weight_decay=0.05,\n",
    "        load_best_model_at_end=True,\n",
    "        fp16=True,\n",
    "        report_to=\"none\",\n",
    "    )\n",
    "\n",
    "    trainer = Trainer(\n",
    "        model=model,\n",
    "        args=training_args,\n",
    "        train_dataset=tokenized[\"train\"],\n",
    "        eval_dataset=tokenized[\"validation\"],\n",
    "        tokenizer=tokenizer,\n",
    "    )\n",
    "\n",
    "    logger.info(\"Starting training\")\n",
    "    trainer.train()\n",
    "\n",
    "    logger.info(\"Saving model\")\n",
    "    trainer.save_model(\"./qa_model_2_roberta\")\n",
    "    tokenizer.save_pretrained(\"./qa_model_2_roberta\")\n",
    "    logger.info(\"Training finished successfully\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eedf9bc9-42c6-4bbf-8a11-6f1c13e99a34",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
